openai:
  chat_model: "gpt-3.5-turbo-16k"
  embedding_model: "text-embedding-ada-002"
qdrant:
    storage_path: "./qdrant_storage"
    host: "localhost"
    port: 6333
    url: "http://localhost:6333"
    embedding_dim: 1536
    document_chart_collection_name: "inflex_document_chart"
    document_collection_name: "inflex_document"
postgresql:
    host: '13.229.68.175'
    port: 5432
    database: 'intflex'
    user: 'postgres'
    password: 'admin123'
